"""add answer scores

Revision ID: da58f863b5e2
Revises: 0b14552bf500
Create Date: 2026-09-19 23:39:15.522544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da58f863b5e2'
down_revision: Union[str, Sequence[str], None] = '0b14552bf500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('correctness_avg', sa.Float(), nullable=True))
    op.add_column('feedback', sa.Column('clarity_avg', sa.Float(), nullable=True))
    op.add_column('feedback', sa.Column('depth_avg', sa.Float(), nullable=True))
    op.add_column('turns', sa.Column('correctness', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('clarity', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('score_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'score_comment')
    op.drop_column('turns', 'depth')
    op.drop_column('turns', 'clarity')
    op.drop_column('turns', 'correctness')
    op.drop_column('feedback', 'depth_avg')
    op.drop_column('feedback', 'clarity_avg')
    op.drop_column('feedback', 'correctness_avg')
    # ### end Alembic commands ###
